version = 0.1
[default.deploy.parameters]
stack_name = "CsvProcessorStack"
resolve_s3 = true
s3_prefix = "CsvProcessorStack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SecretName=\"\""
image_repositories = []
